branches:
  only:
    - netcore-reorg

image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore dotNetRDF.NetCore.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build Libraries/dotNetRDF.Query.Spin
  - dotnet build Testing/Unittest
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF /p:Version=%GitVersion_NuGetVersion%
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF.Data.Virtuoso /p:Version=%GitVersion_NuGetVersion%
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF.Query.FullText /p:Version=%GitVersion_NuGetVersion%

test_script:
  - ps: dotnet test .\Testing\unittest\unittest.csproj -l "trx;LogFileName=tests.trx" --filter category!=explicit --no-build | Out-File .\test.log
  
on_finish:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: Push-AppveyorArtifact .\Testing\unittest\TestResults\output.trx
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Testing\unittest\TestResults\output.trx ) )

artifacts:
  - path: 'nugets\*.nupkg'
  - path: 'Testing\unittest\TestResults\*.trx'
