branches:
  only:
    - netcore-reorg

image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore dotNetRDF.NetCore.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build Libraries/dotNetRDF.Query.Spin
  - dotnet build Testing/Unittest
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF /p:Version=%GitVersion_NuGetVersion%
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF.Data.Virtuoso /p:Version=%GitVersion_NuGetVersion%
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF.Query.FullText /p:Version=%GitVersion_NuGetVersion%

test_script:
  - ps: dotnet test .\Testing\unittest\unittest.csproj -l "trx;LogFileName=output.trx" --filter "category!=explicit&category!=fulltext" --no-build | Out-File .\test.log
  - ps: dotnet test .\Testing\unittest\unittest.csproj -l "trx;LogFileName=fulltext.trx" --filter "category=fulltext" --no-build | Out-File .\test_fulltext.log
  
on_finish:
  - ps: Push-AppveyorArtifact .\Testing\unittest\TestResults\output.trx
  - ps: Push-AppveyorArtifact .\test.log
  - ps: Push-AppveyorArtifact .\test_fulltext.log
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Testing\unittest\TestResults\output.trx ) )
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Testing\unittest\TestResults\fulltext.trx ) )

artifacts:
  - path: 'nugets\*.nupkg'
