branches:
  only:
    - netcore-reorg

image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore dotNetRDF.sln
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

configuration: Release

build_script:
  - dotnet build Libraries/dotNetRDF.Query.Spin
  - dotnet build Testing/Unittest
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF /p:Version=%GitVersion_NuGetVersion%
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF.Data.Virtuoso /p:Version=%GitVersion_NuGetVersion%
  - dotnet pack -c Release -o %APPVEYOR_BUILD_FOLDER%\nugets Libraries/dotNetRDF.Query.FullText /p:Version=%GitVersion_NuGetVersion%

test_script:
  - ps: |
      dotnet test .\Testing\unittest\unittest.csproj -l "trx;LogFileName=output.trx" --filter category!=explicit --no-build | Out-File .\test.log
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
      dotnet test .\Testing\unittest\unittest.csproj -l "trx;LogFileName=fulltext.trx" --filter category=fulltext --no-build | Out-File .\fulltext.log
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
  
on_finish:
  - ps: |
      $ws = (New-Object 'System.Net.WebClient')
      if((Test-Path .\Testing\unittest\TestResults\output.trx)) {    
        Push-AppveyorArtifact .\Testing\unittest\TestResults\output.trx
        Push-AppveyorArtifact .\test.log
        $ws.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Testing\unittest\TestResults\output.trx ) )
      }
      if((Test-Path .\Testing\unittest\TestResults\fulltext.trx)) {
        Push-AppveyorArtifact .\Testing\unittest\TestResults\fulltext.trx
        Push-AppveyorArtifact .\fulltext.log
        $ws.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Testing\unittest\TestResults\fulltext.trx ) )
      }

artifacts:
  - path: 'nugets\*.nupkg'
