branches:
  only:
    - netcore-reorg

install:
  - choco install gitversion.portable -pre -y

before_build:
  - dotnet restore
  - ps: gitversion /l console /output buildserver /updateassemblyinfo
  - ps: Get-ChildItem -Filter project.json -Recurse | % { start-process dotnet -ArgumentList version,$env:GitVersion_LegacySemVer -wo $_.Directory.FullName -NoNewWindow }

configuration: Release

build_script:
  - dotnet build ./**/project.json 
  - dotnet pack -c Release -o nugets Libraries/dotNetRDF
  - dotnet pack -c Release -o nugets Libraries/dotNetRDF.Data.Virtuoso
  - dotnet pack -c Release -o nugets Libraries/dotNetRDF.Query.FullText

test_script:
  - dotnet test Testing/Unittest
  
on_finish:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

artifacts:
  - path: 'nugets\*.nupkg'
  - path: 'TestResult.xml'
