name: build-and-test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'

    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.10
      with:
        useConfigFile: true
      
    - name: Show GitVersion Value
      run: |
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.NuGetVersionV2 }}"
        echo "NuGetVersion: ${{ steps.gitversion.outputs.NuGetVersion }}"
        echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}"
        echo "NuGetPreReleaseTag: ${{ steps.gitversion.outputs.NuGetPreReleaseTag }}"
        
    - name: Build solution
      run: dotnet build dotNetRDF.sln --configuration=Release
    
    - name: Core Tests (.NET 4.7.2)
      run: |
        dotnet test -c Release --filter "Category!=explicit" --framework net472 Testing\unittest\unittest.csproj
        dotnet test -c Release --filter "Category=fulltext" --framework net472
    
    - name: Core Tests (.NET Core 3.1)
      run: |
        dotnet test -c Release --filter "Category!=explicit" --framework netcoreapp3.1 Testing\unittest\unittest.csproj