name: Build and Test
on: push
jobs:
  setup:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.10
      with:
        versionSpec: '5.x'
    
  build:
    needs: setup
    runs-on: windows-latest
    steps:
    - name: GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.10
      with:
        useConfigFile: true
      
    - name: Show GitVersion Value
      run: |
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.NuGetVersionV2 }}"
        echo "NuGetVersion: ${{ steps.gitversion.outputs.NuGetVersion }}"
        echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}"
        echo "NuGetPreReleaseTag: ${{ steps.gitversion.outputs.NuGetPreReleaseTag }}"
        
    - name: Build solution
      run: dotnet build dotNetRDF.sln --configuration=Release
    
  coreTests:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        framework: ["net472", "netcoreapp3.1"]
        suite: ["unittest", "dotNetRdf.Dynamic.Tests", "dotNetRdf.Inferencing.Tests", "dotNetRdf.Ontology.Tests", "dotNetRdf.Shacl.Tests", "dotNetRDF.Skos.Tests"]
    steps:
    - name: Core Tests
      run: dotnet test -c Release --no-build --filter "Category!=explicit" --framework ${{ matrix.framework }} Testing\${{matrix.suite}}
   
  fullTextTests:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Test Full-Text Indexing
      run: dotnet test -c Release --filter "Category=fulltext" --framework net472
    