name: Publish packages
on:
  push:
    tags:
      - "v*"
    
jobs:
  nuget:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Write release version
      shell: bash
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Build solution
      run: dotnet pack --configuration=Release -p:Version=${{ env.VERSION }} -p:PackageOutputPath=../../nugets
      
    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: nugets\*.nupkg

    - name: Publish NuGet Packages
      if: false
      run: nuget push nugets\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.NUGET_API_KEY }}

  release:
    runs-on: windows-latest
    needs: [nuget, docs]
    
    steps:
    - name: Get Binaries
      id: get_binaries
      uses: actions/download-artifact@v4
      with:
        name: nuget
    - name: List downloads
      run: ls -R
      shell: bash
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        prerelease: true
        files: |
          *.nupkg
        
          
      
