name: Publish packages
on:
  push:
    tags:
      - "v*"
    
jobs:
  nuget:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Write release version
      shell: bash
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Build solution
      run: dotnet pack --configuration=Release -p:Version=${VERSION} -p:PackageOutputPath=../../nugets
      
    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: nugets\*.nupkg

    - name: Publish NuGet Packages
      if: false
      run: nuget push nugets\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.NUGET_API_KEY }}

  docs:
    if: false
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install Sandcastle
      run: choco install sandcastle --version 2022.2.6.0
      
    - name: Build Assemblies
      run: dotnet build dotNetRdf.sln
      
    - name: Build Docs
      run: dotnet build Build\shfb\dotnetrdf.shfbproj /p:SHFBROOT="C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder"
   
    - name: Get version tag
      id: version_tag
      run: |
        [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit
        echo "::set-output name=value::${GITHUB_REF#refs/tags/}"
      shell: bash
        
    - name: Create Release Zip
      run: 7z a -tzip dotNetRdf_apidocs_${{ steps.version_tag.outputs.value }}.zip Help
      working-directory: Build\shfb
      
    - name: Upload Release zip
      uses: actions/upload-artifact@v3
      with:
        name: help
        path: Build\shfb\*.zip
          
  
  release:
    runs-on: windows-latest
    needs: [nuget, docs]
    
    steps:
    - name: Get Binaries
      id: get_binaries
      uses: actions/download-artifact@v3
      with:
        name: nuget
    - name: Get Help
      id: get_help
      uses: actions/download-artifact@v3
      with:
        name: help
    - name: List downloads
      run: ls -R
      shell: bash
    - name: Create Relase
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        prerelease: true
        files: |
          *.zip
          *.nupkg
        
          
      
